export const cardStyles = {
  cardContainer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  card: {
    minWidth: "300px",
    maxWidth: "300px",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "8px",
    transition: "all 0.3s ease",
    display: "flex",
    flexDirection: "column",
  },
  cardContent: {
    display: "flex",
    color: "black",
    justifyContent: "center",
    flexDirection: "column",
    padding: "24px",
  },
  cardHeader: {
    fontWeight: "600",
    fontSize: "16px",
    color: "black",
    marginBottom: "8px",
  },
  cardDescription: {
    color: "black",
    fontFamily: " Helvetica, Arial, sans-serif ",
    fontSize: "14px",
    lineHeight: "1.4",
    whiteSpace: "pre-line",
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    height: "40px",
    backgroundColor: "white",
    margin: "0px -16px -11px -16px",
    borderRadius: "0 0 10px 10px",
    padding: "10px",
  },
  cardFooterText: {
    color: "gray",
    fontFamily: " Helvetica, Arial, sans-serif ",
  },
};
